FROM node:lts-alpine
ENV NODE_ENV=development
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --silent
COPY . .

COPY docker-entrypoint.sh ./
RUN chmod +x /usr/src/app/docker-entrypoint.sh

EXPOSE 3000 9229
RUN chown -R node /usr/src/app
USER node

ENTRYPOINT ["/usr/src/app/docker-entrypoint.sh"]
CMD ["npm", "run", "dev"]
